version: '3.8'

services:
  trading-algo:
    build: .
    ports:
      - "3001:3001"  # Backend API
      - "3000:3000"  # Frontend
    volumes:
      - ./trading.db:/app/backend/trading.db  # Persist database
      - ./logs:/app/backend/logs              # Persist logs
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TZ=America/Los_Angeles  # PST timezone for scheduler
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
