version: '3.8'

services:
  trading-algo:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Backend
    volumes:
      # Mount source code for hot reload
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      # Persist database
      - ./data:/app/data
      # Exclude node_modules from volume mounts
      - /app/backend/node_modules
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/trading.db
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_PAPER=${ALPACA_PAPER:-true}
    stdin_open: true
    tty: true

  # Production build
  trading-algo-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/trading.db
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_PAPER=${ALPACA_PAPER:-true}
    profiles:
      - production
